CC = gcc
LIB = -lsocket -lnsl

all: server client

server:
	${CC} -m64 -o myftpserver myftpserver.c myftp.c ${LIB} -lpthread

client:
	${CC} -m64 -o myftpclient myftpclient.c myftp.c ${LIB}

clean:
	rm myftpserver
	rm myftpclient
